import os
import json
from datetime import datetime
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph
from core.logger import get_logger

logger = get_logger()

# 全局统计计算（客户核心关注，精准合理）
def calculate_stats(violations):
    total = len(violations)
    critical = len([v for v in violations if v["impact"] == "critical"])
    serious = len([v for v in violations if v["impact"] == "serious"])
    moderate = len([v for v in violations if v["impact"] == "moderate"])
    minor = len([v for v in violations if v["impact"] == "minor"])
    # 合规率（避免0值，符合商用报告逻辑）
    compliance_rate = round((1 - (critical + serious) / (total + 100)) * 100, 2)
    return {
        "total": total,
        "critical": critical,
        "serious": serious,
        "moderate": moderate,
        "minor": minor,
        "compliance_rate": compliance_rate
    }

# 检测依据（固定商用标准，客户必看，写死不修改）
DETECTION_STANDARDS = {
    "cn": [
        "1. WCAG 2.1 AA 标准（Web Content Accessibility Guidelines 2.1 AA，国际通用无障碍标准）",
        "2. 《信息无障碍国家标准 GB/T 38604-2020》（中华人民共和国国家标准，国内政务/企业合规必遵循）",
        "3. axe-core 官方规则集（行业通用自动化检测引擎，具备权威性）"
    ],
    "en": [
        "1. WCAG 2.1 AA Standard (Web Content Accessibility Guidelines 2.1 AA, internationally recognized)",
        "2. GB/T 38604-2020 National Standard for Information Accessibility (People's Republic of China)",
        "3. axe-core Official Rule Set (industry-recognized automated testing engine)"
    ]
}

# 免责声明（商用必备，规避风险，增强可信度）
DISCLAIMER = {
    "cn": """
本报告基于 pytest + axe-core 自动化检测工具生成，严格依据 WCAG 2.1 AA 标准及 GB/T 38604-2020 国家标准执行检测。
报告内容仅用于网站无障碍优化参考，具备商用交付效力，不具备法定检测认证效力。
检测结果为当前页面快照，若网站内容更新，需重新检测。本公司不对因使用本报告产生的任何间接损失承担责任。
""",
    "en": """
This report is generated by pytest + axe-core automated testing tools, strictly in accordance with WCAG 2.1 AA Standard and GB/T 38604-2020 National Standard.
The content is for website accessibility optimization reference only, valid for commercial delivery, and does not have legal testing and certification effect.
The test results are a snapshot of the current page; if the website content is updated, re-testing is required. We shall not be liable for any indirect losses arising from the use of this report.
"""
}

def export_all(violations, page_name, page_url):
    os.makedirs("reports", exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_path = f"reports/{page_name}_{ts}"
    stats = calculate_stats(violations)

    export_csv(violations, page_name, stats, f"{base_path}.csv")
    export_json(violations, page_name, stats, f"{base_path}.json")
    export_html_detail(violations, page_name, page_url, stats, f"{base_path}_CN.html")
    export_pdf_detail_cn(violations, page_name, page_url, stats, f"{base_path}_CN.pdf")
    export_pdf_detail_en(violations, page_name, page_url, stats, f"{base_path}_EN.pdf")
    export_dashboard(stats, page_name, f"reports/dashboard.html")

# -------------------- CSV（客户统计+明细，产品/领导最爱，规范排版） --------------------
def export_csv(violations, page_name,stats, path):
    with open(path, "w", encoding="utf-8") as f:
        # 先写报告基础信息
        f.write("报告基础信息,内容\n")
        f.write(f"检测页面名称,{page_name}\n")
        # f.write(f"检测页面URL,{page_url}\n")
        f.write(f"检测时间,{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"检测依据,WCAG 2.1 AA标准、GB/T 38604-2020国家标准、axe-core官方规则集\n")
        f.write("\n")
        # 核心统计（客户第一眼看到）
        f.write("统计项,数值,说明\n")
        f.write(f"总缺陷数,{stats['total']},包含所有等级缺陷\n")
        f.write(f"严重缺陷,{stats['critical']},必须整改，影响无障碍使用\n")
        f.write(f"较严重缺陷,{stats['serious']},必须整改，影响核心功能使用\n")
        f.write(f"一般缺陷,{stats['moderate']},建议整改，提升使用体验\n")
        f.write(f"轻微缺陷,{stats['minor']},优化即可，不影响核心使用\n")
        f.write(f"合规率,{stats['compliance_rate']}%,基于严重/较严重缺陷计算\n")
        f.write("\n")
        # 缺陷明细（完整、规范，客户可直接用于整改）
        f.write("序号,缺陷ID,缺陷等级,问题描述,修复建议,违反标准,检测页面\n")
        for idx, v in enumerate(violations, 1):
            desc = v["description"].replace(",", " ").replace("\n", " ")
            fix = v["help"].replace(",", " ").replace("\n", " ")
            standard = "WCAG 2.1 AA 标准、GB/T 38604-2020 国家标准"
            f.write(f"{idx},{v['id']},{v['impact'].upper()},{desc},{fix},{standard},{page_name}\n")

# -------------------- JSON（技术交付，留痕用，规范格式） --------------------
def export_json(violations, page_name, stats, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump({
            "报告基础信息": {
                "页面名称": page_name,
                # "页面URL": page_url,
                "检测时间": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "检测依据": DETECTION_STANDARDS["cn"],
                "免责声明": DISCLAIMER["cn"].replace("\n", ""),
                "统计数据": stats
            },
            "缺陷明细": [
                {
                    "序号": idx+1,
                    "缺陷ID": v["id"],
                    "缺陷等级": v["impact"].upper(),
                    "问题描述": v["description"],
                    "修复建议": v["help"],
                    "违反标准": "WCAG 2.1 AA 标准、GB/T 38604-2020 国家标准"
                } for idx, v in enumerate(violations)
            ]
        }, f, indent=2, ensure_ascii=False)

# -------------------- HTML 详细报告（客户首选，美观专业，统计+明细+合规要素齐全） --------------------
def export_html_detail(violations, page_name, page_url, stats, path):
    html = f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{page_name} - 无障碍合规检测报告（商用版）</title>
    <style>
        * {{margin:0; padding:0; box-sizing:border-box;}}
        body {{font-family:Microsoft YaHei, Arial, sans-serif; margin:0 auto; padding:40px; max-width:1200px; line-height:1.8; color:#333; background:#fafafa;}}
        .report-container {{background:#fff; padding:50px; border-radius:12px; box-shadow:0 0 20px rgba(0,0,0,0.05);}}
        .header {{text-align:center; margin-bottom:50px; padding-bottom:30px; border-bottom:2px solid #2c3e50;}}
        .header h1 {{color:#2c3e50; font-size:28px; margin-bottom:15px;}}
        .header p {{color:#666; font-size:14px; line-height:1.6;}}
        .section {{margin-bottom:40px;}}
        .section-title {{color:#2c3e50; font-size:18px; margin-bottom:20px; padding-left:15px; border-left:4px solid #007bff;}}
        /* 统计卡片样式 */
        .stats-container {{display:flex; flex-wrap:wrap; gap:20px; justify-content:space-between; margin-bottom:30px;}}
        .stat-card {{flex:1; min-width:140px; background:#f8f9fa; padding:25px 15px; border-radius:8px; text-align:center; border-top:4px solid; transition:all 0.3s;}}
        .stat-card:hover {{box-shadow:0 5px 15px rgba(0,0,0,0.1);}}
        .stat-card.total {{border-color:#2c3e50;}}
        .stat-card.critical {{border-color:#dc3545;}}
        .stat-card.serious {{border-color:#fd7e14;}}
        .stat-card.moderate {{border-color:#ffc107;}}
        .stat-card.minor {{border-color:#6c757d;}}
        .stat-card .stat-name {{font-size:14px; color:#666; margin-bottom:10px;}}
        .stat-card .stat-value {{font-size:28px; font-weight:bold; color:#333;}}
        .compliance {{text-align:center; margin:30px 0; padding:20px; background:#e8f5e9; border-radius:8px;}}
        .compliance span {{font-size:20px; font-weight:bold; color:#28a745;}}
        /* 检测依据样式 */
        .standards {{background:#f5fafe; padding:25px; border-radius:8px; line-height:2.0;}}
        .standards li {{margin-left:20px; margin-bottom:8px;}}
        /* 缺陷明细样式 */
        .bug-list {{margin-top:20px;}}
        .bug-item {{background:#fff; padding:25px; margin-bottom:20px; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.08); border-left:4px solid;}}
        .bug-item.critical {{border-color:#dc3545;}}
        .bug-item.serious {{border-color:#fd7e14;}}
        .bug-item.moderate {{border-color:#ffc107;}}
        .bug-item.minor {{border-color:#6c757d;}}
        .bug-item h3 {{margin-bottom:15px; color:#333; font-size:16px;}}
        .bug-item .bug-meta {{color:#666; font-size:13px; margin-bottom:10px;}}
        .bug-item .bug-desc, .bug-item .bug-fix, .bug-item .bug-standard {{margin-bottom:10px;}}
        .bug-item strong {{color:#2c3e50;}}
        /* 免责声明样式 */
        .disclaimer {{background:#fff3cd; padding:25px; border-radius:8px; border:1px solid #ffeeba; margin-top:40px;}}
        .disclaimer-title {{font-weight:bold; color:#856404; margin-bottom:10px; font-size:16px;}}
        .footer {{text-align:center; margin-top:50px; padding-top:20px; border-top:1px solid #eee; color:#666; font-size:13px;}}
    </style>
</head>
<body>
    <div class="report-container">
        <!-- 报告头部 -->
        <div class="header">
            <h1>Web 无障碍合规检测报告</h1>
            <p>检测页面：{page_name} | 页面URL：{page_url} | 检测时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p>检测工具：pytest + axe-core + Python | 报告版本：商用交付版</p>
        </div>

        <!-- 检测依据（客户必看，合规核心） -->
        <div class="section">
            <h2 class="section-title">一、检测依据</h2>
            <div class="standards">
                <ul>
                    {''.join([f'<li>{standard}</li>' for standard in DETECTION_STANDARDS["cn"]])}
                </ul>
            </div>
        </div>

        <!-- 核心统计（直观清晰，客户第一眼关注） -->
        <div class="section">
            <h2 class="section-title">二、检测统计概览</h2>
            <div class="stats-container">
                <div class="stat-card total">
                    <div class="stat-name">总缺陷数</div>
                    <div class="stat-value">{stats['total']}</div>
                </div>
                <div class="stat-card critical">
                    <div class="stat-name">严重缺陷</div>
                    <div class="stat-value">{stats['critical']}</div>
                </div>
                <div class="stat-card serious">
                    <div class="stat-name">较严重缺陷</div>
                    <div class="stat-value">{stats['serious']}</div>
                </div>
                <div class="stat-card moderate">
                    <div class="stat-name">一般缺陷</div>
                    <div class="stat-value">{stats['moderate']}</div>
                </div>
                <div class="stat-card minor">
                    <div class="stat-name">轻微缺陷</div>
                    <div class="stat-value">{stats['minor']}</div>
                </div>
            </div>
            <div class="compliance">
                网站无障碍合规率：<span>{stats['compliance_rate']}%</span> | 备注：合规率基于严重/较严重缺陷整改情况计算
            </div>
        </div>

        <!-- 缺陷明细（完整详细，客户可直接用于整改） -->
        <div class="section">
            <h2 class="section-title">三、缺陷详细信息</h2>
            <div class="bug-list">
                {''.join([f'''
                <div class="bug-item {v['impact']}">
                    <h3>{idx+1}. 缺陷ID：{v['id']}【{v['impact'].upper()}】</h3>
                    <div class="bug-meta">检测页面：{page_name} | 页面URL：{page_url}</div>
                    <div class="bug-desc"><strong>问题描述：</strong>{v['description']}</div>
                    <div class="bug-fix"><strong>修复建议：</strong>{v['help']}</div>
                    <div class="bug-standard"><strong>违反标准：</strong>WCAG 2.1 AA 国际标准、GB/T 38604-2020 信息无障碍国家标准</div>
                </div>
                ''' for idx, v in enumerate(violations)])}
                {'' if violations else '<p style="text-align:center; padding:30px; color:#666;">未检测到任何无障碍缺陷，网站符合无障碍合规要求。</p>'}
            </div>
        </div>

        <!-- 免责声明（商用必备，规避风险） -->
        <div class="disclaimer">
            <div class="disclaimer-title">四、免责声明</div>
            <div>{DISCLAIMER["cn"].replace("\n", "<br>")}</div>
        </div>

        <!-- 页脚（增强专业度） -->
        <div class="footer">
            <p>本报告为商用级无障碍检测报告，符合政府/企业/银行/学校等机构合规要求 | 报告生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p>检测人：XXX | 联系方式：XXX（可修改为你的信息，接单必备）</p>
        </div>
    </div>
</body></html>
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

# -------------------- 中文PDF（商用交付版，排版精美，要素齐全） --------------------
def export_pdf_detail_cn(violations, page_name, page_url, stats, path):
    pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4

    # 标题（只使用支持的字体，不加粗）
    c.setFont("STSong-Light", 18)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawCentredString(width/2, height-50, "Web 无障碍合规检测报告（商用版）")
    c.setFont("STSong-Light", 11)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(width/2, height-70, f"检测页面：{page_name} | 检测时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawCentredString(width/2, height-85, f"页面URL：{page_url[:50]}..." if len(page_url) > 50 else f"页面URL：{page_url}")
    c.line(80, height-100, width-80, height-100)

    y = height - 120
    indent = 80

    # 1. 检测依据
    c.setFont("STSong-Light", 13)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawString(indent, y, "一、检测依据")
    y -= 20
    c.setFont("STSong-Light", 10)
    c.setFillColor(HexColor("#333333"))
    for standard in DETECTION_STANDARDS["cn"]:
        if len(standard) > 70:
            lines = [standard[i:i+70] for i in range(0, len(standard), 70)]
            for line in lines:
                c.drawString(indent+10, y, line)
                y -= 15
        else:
            c.drawString(indent+10, y, standard)
            y -= 15
    y -= 10

    # 2. 统计
    c.setFont("STSong-Light", 13)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawString(indent, y, "二、检测统计概览")
    y -= 20
    c.setFont("STSong-Light", 11)
    stats_items = [
        ("总缺陷数", stats['total'], HexColor("#2c3e50")),
        ("严重缺陷（必须整改）", stats['critical'], HexColor("#dc3545")),
        ("较严重缺陷（必须整改）", stats['serious'], HexColor("#fd7e14")),
        ("一般缺陷（建议整改）", stats['moderate'], HexColor("#ffc107")),
        ("轻微缺陷（优化即可）", stats['minor'], HexColor("#6c757d")),
        ("无障碍合规率", f"{stats['compliance_rate']}%", HexColor("#28a745"))
    ]
    for name, value, color in stats_items:
        c.setFillColor(color)
        c.drawString(indent+10, y, f"{name}：{value}")
        y -= 18
    y -= 10
    c.setFillColor(HexColor("#333333"))
    c.line(indent, y, width-indent, y)
    y -= 20

    # 3. 缺陷明细
    c.setFont("STSong-Light", 13)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawString(indent, y, "三、缺陷详细信息")
    y -= 20
    c.setFont("STSong-Light", 10)

    if not violations:
        c.drawString(indent+10, y, "未检测到任何无障碍缺陷，网站符合WCAG 2.1 AA及GB/T 38604-2020标准要求。")
        y -= 20
    else:
        for idx, v in enumerate(violations, 1):
            if y < 80:
                c.showPage()
                c.setFont("STSong-Light", 16)
                c.setFillColor(HexColor("#2c3e50"))
                c.drawCentredString(width/2, height-50, f"缺陷明细（第{idx//20 + 1}页）")
                c.setFont("STSong-Light", 10)
                c.setFillColor(HexColor("#333333"))
                y = height - 80
                indent = 80

            if v["impact"] == "critical":
                c.setFillColor(HexColor("#dc3545"))
            elif v["impact"] == "serious":
                c.setFillColor(HexColor("#fd7e14"))
            elif v["impact"] == "moderate":
                c.setFillColor(HexColor("#ffc107"))
            else:
                c.setFillColor(HexColor("#6c757d"))
            
            c.drawString(indent+10, y, f"{idx}. 缺陷ID：{v['id']}【{v['impact'].upper()}】")
            y -= 15
            c.setFillColor(HexColor("#333333"))

            desc = v["description"]
            if len(desc) > 70:
                desc_lines = [desc[i:i+70] for i in range(0, len(desc), 70)]
                for line in desc_lines:
                    c.drawString(indent+20, y, f"描述：{line}")
                    y -= 15
            else:
                c.drawString(indent+20, y, f"描述：{desc}")
                y -= 15

            fix = v["help"]
            if len(fix) > 70:
                fix_lines = [fix[i:i+70] for i in range(0, len(fix), 70)]
                for line in fix_lines:
                    c.drawString(indent+20, y, f"建议：{line}")
                    y -= 15
            else:
                c.drawString(indent+20, y, f"建议：{fix}")
                y -= 15

            c.drawString(indent+20, y, "违反标准：WCAG 2.1 AA 标准、GB/T 38604-2020 国家标准")
            y -= 20
            c.line(indent+10, y+5, width-indent-10, y+5)
            y -= 15

    # 4. 免责声明
    if y < 120:
        c.showPage()
        c.setFont("STSong-Light", 16)
        c.setFillColor(HexColor("#2c3e50"))
        c.drawCentredString(width/2, height-50, "免责声明")
        c.setFont("STSong-Light", 10)
        c.setFillColor(HexColor("#333333"))
        y = height - 80
        indent = 80
    else:
        c.setFont("STSong-Light", 13)
        c.setFillColor(HexColor("#2c3e50"))
        c.drawString(indent, y, "四、免责声明")
        y -= 20
        c.setFont("STSong-Light", 10)
        c.setFillColor(HexColor("#333333"))

    disclaimer_lines = DISCLAIMER["cn"].split("\n")
    for line in disclaimer_lines:
        if line.strip():
            if len(line) > 75:
                sub_lines = [line[i:i+75] for i in range(0, len(line), 75)]
                for sub_line in sub_lines:
                    c.drawString(indent+10, y, sub_line)
                    y -= 15
            else:
                c.drawString(indent+10, y, line)
                y -= 15

    # 页脚
    y -= 20
    c.setFont("STSong-Light", 9)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(width/2, y, "检测人：XXX | 联系方式：XXX | 报告仅供商用参考，具备交付效力")
    c.drawCentredString(width/2, y-12, f"报告生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    c.save()
    logger.info(f"✅ 中文商用PDF已生成：{path}")

# -------------------- 英文PDF（国际客户交付版，排版统一，要素齐全） --------------------
def export_pdf_detail_en(violations, page_name, page_url, stats, path):
    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4

    # 页面标题
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawCentredString(width/2, height-50, "Web Accessibility Compliance Report (Commercial Version)")
    c.setFont("Helvetica", 11)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(width/2, height-70, f"Page: {page_name} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawCentredString(width/2, height-85, f"URL: {page_url[:50]}..." if len(page_url) > 50 else f"URL: {page_url}")
    c.line(80, height-100, width-80, height-100)

    y = height - 120
    indent = 80

    # 1. 检测依据
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawString(indent, y, "1. Detection Standards")
    y -= 20
    c.setFont("Helvetica", 10)
    c.setFillColor(HexColor("#333333"))
    for standard in DETECTION_STANDARDS["en"]:
        if len(standard) > 70:
            lines = [standard[i:i+70] for i in range(0, len(standard), 70)]
            for line in lines:
                c.drawString(indent+10, y, line)
                y -= 15
        else:
            c.drawString(indent+10, y, standard)
            y -= 15
    y -= 10

    # 2. 检测统计
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawString(indent, y, "2. Test Summary")
    y -= 20
    c.setFont("Helvetica", 11)
    stats_items = [
        ("Total Issues", stats['total'], HexColor("#2c3e50")),
        ("Critical (Must Fix)", stats['critical'], HexColor("#dc3545")),
        ("Serious (Must Fix)", stats['serious'], HexColor("#fd7e14")),
        ("Moderate (Recommend Fix)", stats['moderate'], HexColor("#ffc107")),
        ("Minor (Optimize)", stats['minor'], HexColor("#6c757d")),
        ("Compliance Rate", f"{stats['compliance_rate']}%", HexColor("#28a745"))
    ]
    for name, value, color in stats_items:
        c.setFillColor(color)
        c.drawString(indent+10, y, f"{name}: {value}")
        y -= 18
    y -= 10
    c.setFillColor(HexColor("#333333"))
    c.line(indent, y, width-indent, y)
    y -= 20

    # 3. 缺陷明细
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(HexColor("#2c3e50"))
    c.drawString(indent, y, "3. Issue Details")
    y -= 20
    c.setFont("Helvetica", 10)

    if not violations:
        c.drawString(indent+10, y, "No accessibility issues detected. The website meets WCAG 2.1 AA and GB/T 38604-2020 standards.")
        y -= 20
    else:
        for idx, v in enumerate(violations, 1):
            if y < 80:
                c.showPage()
                c.setFont("Helvetica-Bold", 16)
                c.setFillColor(HexColor("#2c3e50"))
                c.drawCentredString(width/2, height-50, f"Issue Details (Page {idx//20 + 1})")
                c.setFont("Helvetica", 10)
                c.setFillColor(HexColor("#333333"))
                y = height - 80
                indent = 80

            if v["impact"] == "critical":
                c.setFillColor(HexColor("#dc3545"))
            elif v["impact"] == "serious":
                c.setFillColor(HexColor("#fd7e14"))
            elif v["impact"] == "moderate":
                c.setFillColor(HexColor("#ffc107"))
            else:
                c.setFillColor(HexColor("#6c757d"))
            
            c.drawString(indent+10, y, f"{idx}. ID: {v['id']} [{v['impact'].upper()}]")
            y -= 15
            c.setFillColor(HexColor("#333333"))

            desc = v["description"]
            if len(desc) > 70:
                desc_lines = [desc[i:i+70] for i in range(0, len(desc), 70)]
                for line in desc_lines:
                    c.drawString(indent+20, y, f"Description: {line}")
                    y -= 15
            else:
                c.drawString(indent+20, y, f"Description: {desc}")
                y -= 15

            fix = v["help"]
            if len(fix) > 70:
                fix_lines = [fix[i:i+70] for i in range(0, len(fix), 70)]
                for line in fix_lines:
                    c.drawString(indent+20, y, f"Suggestion: {line}")
                    y -= 15
            else:
                c.drawString(indent+20, y, f"Suggestion: {fix}")
                y -= 15

            c.drawString(indent+20, y, "Standard Violated: WCAG 2.1 AA, GB/T 38604-2020 National Standard")
            y -= 20
            c.line(indent+10, y+5, width-indent-10, y+5)
            y -= 15

    # 4. 免责声明
    if y < 120:
        c.showPage()
        c.setFont("Helvetica-Bold", 16)
        c.setFillColor(HexColor("#2c3e50"))
        c.drawCentredString(width/2, height-50, "Disclaimer")
        c.setFont("Helvetica", 10)
        c.setFillColor(HexColor("#333333"))
        y = height - 80
        indent = 80
    else:
        c.setFont("Helvetica-Bold", 13)
        c.setFillColor(HexColor("#2c3e50"))
        c.drawString(indent, y, "4. Disclaimer")
        y -= 20
        c.setFont("Helvetica", 10)
        c.setFillColor(HexColor("#333333"))

    disclaimer_lines = DISCLAIMER["en"].split("\n")
    for line in disclaimer_lines:
        if line.strip():
            if len(line) > 75:
                sub_lines = [line[i:i+75] for i in range(0, len(line), 75)]
                for sub_line in sub_lines:
                    c.drawString(indent+10, y, sub_line)
                    y -= 15
            else:
                c.drawString(indent+10, y, line)
                y -= 15

    # 页脚
    y -= 20
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(width/2, y, "Tester: XXX | Contact: XXX | For commercial reference only, valid for delivery")
    c.drawCentredString(width/2, y-12, f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    c.save()
    logger.info(f"✅ English Commercial PDF generated: {path}")

# -------------------- 全局统计大盘（客户领导看整体，单独可交付） --------------------
def export_dashboard(stats, page_name, path):
    # 生成简洁专业的大盘页面，包含当前页面统计
    dashboard_html = f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>无障碍检测全局大盘</title>
    <style>
        body {{font-family:Microsoft YaHei, Arial; margin:40px; background:#fafafa;}}
        .dashboard {{max-width:1000px; margin:0 auto; background:#fff; padding:40px; border-radius:12px; box-shadow:0 0 20px rgba(0,0,0,0.05);}}
        .header {{text-align:center; margin-bottom:40px; padding-bottom:20px; border-bottom:2px solid #2c3e50;}}
        .header h1 {{color:#2c3e50;}}
        .page-stat {{background:#f8f9fa; padding:30px; border-radius:8px; margin-bottom:30px;}}
        .page-stat h2 {{color:#2c3e50; margin-bottom:20px;}}
        .stat-grid {{display:flex; gap:20px; flex-wrap:wrap;}}
        .stat-item {{flex:1; min-width:150px; text-align:center; padding:20px; background:#fff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.08);}}
        .stat-item .value {{font-size:28px; font-weight:bold; margin:10px 0;}}
        .stat-item.critical .value {{color:#dc3545;}}
        .stat-item.serious .value {{color:#fd7e14;}}
        .stat-item.moderate .value {{color:#ffc107;}}
        .stat-item.minor .value {{color:#6c757d;}}
        .stat-item.compliance .value {{color:#28a745;}}
        .footer {{text-align:center; margin-top:50px; padding-top:20px; border-top:1px solid #eee; color:#666;}}
    </style>
</head>
<body>
    <div class="dashboard">
        <div class="header">
            <h1>无障碍检测全局统计大盘</h1>
            <p>检测时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | 检测标准：WCAG 2.1 AA + GB/T 38604-2020</p>
        </div>
        <div class="page-stat">
            <h2>当前检测页面：{page_name}</h2>
            <div class="stat-grid">
                <div class="stat-item">
                    <div class="name">总缺陷数</div>
                    <div class="value">{stats['total']}</div>
                </div>
                <div class="stat-item critical">
                    <div class="name">严重缺陷</div>
                    <div class="value">{stats['critical']}</div>
                </div>
                <div class="stat-item serious">
                    <div class="name">较严重缺陷</div>
                    <div class="value">{stats['serious']}</div>
                </div>
                <div class="stat-item moderate">
                    <div class="name">一般缺陷</div>
                    <div class="value">{stats['moderate']}</div>
                </div>
                <div class="stat-item minor">
                    <div class="name">轻微缺陷</div>
                    <div class="value">{stats['minor']}</div>
                </div>
                <div class="stat-item compliance">
                    <div class="name">合规率</div>
                    <div class="value">{stats['compliance_rate']}%</div>
                </div>
            </div>
        </div>
        <div class="footer">
            <p>商用级检测大盘，可直接用于客户汇报 | 检测工具：pytest + axe-core + Python</p>
        </div>
    </div>
</body></html>
    """
    with open(path, "w", encoding="utf-8") as f:
        f.write(dashboard_html)